import React, { useState } from "react";
import { X, ChevronDown, ChevronRight, Activity, FileCode, ArrowRight, ArrowLeft, Network, Box } from "lucide-react";
import { FileDetail } from "../lib/api";
import { RiskBreakdown } from "./RiskBreakdown";

type Props = {
  file: FileDetail;
  onClose: () => void;
  onSelectFile: (path: string) => void;
  onTraceImpact: (path: string) => void;
  onAskAboutFile?: (path: string) => void;
};

function CollapsibleSection({ title, defaultOpen = true, children, badge }: { title: string, defaultOpen?: boolean, children: React.ReactNode, badge?: number }) {
  const [isOpen, setIsOpen] = useState(defaultOpen);
  return (
    <div className="inspector-section">
      <div className="section-header" onClick={() => setIsOpen(!isOpen)}>
        {isOpen ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
        <span className="title">{title}</span>
        {badge !== undefined && <span className="badge">{badge}</span>}
      </div>
      {isOpen && <div className="section-content">{children}</div>}
    </div>
  );
}

export function Inspector({ file, onClose, onSelectFile, onTraceImpact, onAskAboutFile }: Props) {
  const filename = file.path.split("/").pop() || file.path;
  const isHighRisk = file.load_bearing_score > 75;

  return (
    <aside className="inspector">
      <header className="inspector-header">
        <div className="inspector-title">INSPECTOR</div>
        <button className="close-btn" onClick={onClose}><X size={16} /></button>
      </header>

      <div className="inspector-scroll">
        <div className="file-header">
          <h2>{filename}</h2>
          <div className="file-path">{file.path}</div>
          <div className="file-meta">
            {file.language && <span>{file.language}</span>}
            <span className={`risk-badge ${isHighRisk ? 'high-risk' : ''}`}>
              Risk {Math.round(file.load_bearing_score)}
            </span>
          </div>
        </div>

        <CollapsibleSection title="RISK PROFILE">
          {file.risk_components ? (
            <RiskBreakdown riskComponents={file.risk_components} />
          ) : (
            <div className="metrics-grid">
              <div className="metric">
                <span className="value">{file.loc}</span>
                <span className="label">LOC</span>
              </div>
              <div className="metric">
                <span className="value">{file.dependents.length}</span>
                <span className="label">Dependents</span>
              </div>
              <div className="metric">
                <span className="value">{file.imports.length}</span>
                <span className="label">Imports</span>
              </div>
              <div className="metric">
                <span className="value">{file.complexity}</span>
                <span className="label">Complexity</span>
              </div>
            </div>
          )}
        </CollapsibleSection>
        
        {file.summary && (
          <CollapsibleSection title="AI SUMMARY">
            <div className="ai-summary">
              <p>{file.summary}</p>
              <div className="provenance">Generated by AI</div>
            </div>
          </CollapsibleSection>
        )}

        {file.symbols.length > 0 && (
          <CollapsibleSection title="SYMBOLS" badge={file.symbols.length}>
            <ul className="symbol-list">
              {file.symbols.map((s, i) => (
                <li key={i}>
                  <Box size={12} className="symbol-icon" />
                  <span className="symbol-name">{s.name}</span>
                  <span className="symbol-kind">{s.kind}</span>
                </li>
              ))}
            </ul>
          </CollapsibleSection>
        )}

        {file.imports.length > 0 && (
          <CollapsibleSection title="IMPORTS" badge={file.imports.length}>
            <ul className="dependency-list">
              {file.imports.map((dep, i) => (
                <li key={i} onClick={() => onSelectFile(dep)} className="clickable">
                  <ArrowRight size={12} className="dep-icon" />
                  <span>{dep.split("/").pop()}</span>
                </li>
              ))}
            </ul>
          </CollapsibleSection>
        )}

        {file.dependents.length > 0 && (
          <CollapsibleSection title="DEPENDENTS" badge={file.dependents.length}>
            <ul className="dependency-list">
              {file.dependents.map((dep, i) => (
                <li key={i} onClick={() => onSelectFile(dep)} className="clickable">
                  <ArrowLeft size={12} className="dep-icon" />
                  <span>{dep.split("/").pop()}</span>
                </li>
              ))}
            </ul>
          </CollapsibleSection>
        )}

        {file.external_deps.length > 0 && (
          <CollapsibleSection title="EXTERNAL DEPENDENCIES" badge={file.external_deps.length} defaultOpen={false}>
            <ul className="dependency-list">
              {file.external_deps.map((dep, i) => (
                <li key={i}>
                  <Network size={12} className="dep-icon" />
                  <span>{dep}</span>
                </li>
              ))}
            </ul>
          </CollapsibleSection>
        )}
      </div>

      <footer className="inspector-actions">
        <button className="action-btn primary" onClick={() => onTraceImpact(file.path)}>
          <Activity size={14} /> Trace impact
        </button>
        {onAskAboutFile && (
          <button className="action-btn" onClick={() => onAskAboutFile(file.path)}>
            Ask about file
          </button>
        )}
      </footer>
    </aside>
  );
}
